### ISSUE TITLE
If the tableView has the header, the header does not move with the cell content

### ISSUE THREAD

**Issue by becarefullee** [andreamazz/AMScrollingNavbar#219]
I had a tableView with two different kinds of cells, one for section header, one for the content. The content cell move correctly, however the header cell stuck there until the header of next section come up and push it away.

**Comment by andreamazz** [comment]
Hey @becarefullee 
Can you please provide a sample project with the issue?

**Comment by becarefullee** [comment]
No problem. I modified the code in tableviewcontroller from your demo (just added the header view). 
[AMScrollingNavbar.zip](https://github.com/andreamazz/AMScrollingNavbar/files/555190/AMScrollingNavbar.zip)

**Comment by andreamazz** [comment]
Thanks for that. Let me do some digging, I'll let you know if I can work around it.

**Comment by becarefullee** [comment]
Thanks for paying attention to this issue :)

**Comment by miraz029** [comment]
Is there any update for the issue?

**Comment by NightWarrior** [comment]
Is there any update for the issue? (2)

**Comment by NightWarrior** [comment]
I fixed this issue on my own end. The issue is caused because the contentInset is stopping the tableHeaders to go above what the inset is. To fix it, in in the `scrollViewDidScroll(_ scrollView: UIScrollView)` i updated the inset to follow the topBar.

The issue was finding the right values and arithmetics between them. Finally the correct form was:
`tableView.contentInset = UIEdgeInsets(top: topBar.frame.height + topBar.frame.origin.y - (navigationController?.navigationBar.frame.height)! - UIApplication.shared.statusBarFrame.height , left: 0, bottom: 0, right: 0)` 
You just need to subtract the statusbar height and navigationbar height and add height and y position of the bar which is following your scroll and tableview content.

I'm guessing AMScrollingNavbar can expose a method which calculates the value like i did and return it. And the user will only have to update his inset in the scrollviewDidScroll method. 

Hope it helps someone.

**Comment by andreamazz** [comment]
@NightWarrior 
nice find! With `topBar` you mean the navigation bar?  
I think I can add a delegate method for that, something like `shouldUpdateContentInset`

**Comment by NightWarrior** [comment]
"topBar you mean the navigation bar?"
Hmmm, sorry, let me be more clear, i'm talking about the bar that you're using in the Extension view in your demo app. I'm using something similar. So my sectionheaders were stopping below it while rows were going above it behind it.

**Comment by NightWarrior** [comment]
Update: If you have ios11 searchbar (searchcontroller inside navigationItem) then you need to subtract another value

`var ios11SearchBarHeight:CGFloat = 0.0
        if #available(iOS 11.0, *) {
            if let height:CGFloat = self.navigationItem.searchController?.searchBar.frame.height {
                ios11SearchBarHeight = height
            }
        }
        self.tableView?.contentInset = UIEdgeInsets(top: 50 + (topBar?.frame.origin.y)! - (navigationController?.navigationBar.frame.height)! - UIApplication.shared.statusBarFrame.height - ios11SearchBarHeight , left: 0, bottom: 0, right: 0)`

And again, topBar is an extended view that i have placed under my navigationbar and it follows the tableview scroll.

**Comment by andreamazz** [comment]
Ok, I think I got it, I've added a couple of lines that take care of the contentInset automatically. The sample project now has a section header, and it's scrolling correctly. Checkout commit afcdf84 and let me know.

**Comment by NightWarrior** [comment]
I tested it, it works fine, right up until i put in a ios11 searchcontroller in the navigationItem... the first bit of movement can set it off... And it doesnt recover after it. If you move it slightly and dont expand the searchbar fully then it breaks....

<img width="321" alt="screen shot 2017-12-21 at 10 17 43 am" src="https://user-images.githubusercontent.com/3524885/34241589-650fb852-e638-11e7-9566-ea6583117da1.png">
<img width="321" alt="screen shot 2017-12-21 at 10 15 50 am" src="https://user-images.githubusercontent.com/3524885/34241590-6543db00-e638-11e7-855b-36e585b89cbc.png">


(P.S i didnt pull the code, only made the changes in the demo project copy that i had.)

**Comment by NightWarrior** [comment]
Also, found another issue that i believe stems from this issue as well(adjusting the insets)... Scroll down and tap at top to scroll to top... The content hides behind the topBar... 
<img width="322" alt="screen shot 2017-12-21 at 10 24 41 am" src="https://user-images.githubusercontent.com/3524885/34241708-2fc815c6-e639-11e7-83c7-7db05fbc577c.png">

In my own application i had to scroll up after a servercall and i was doing it by changing the contentOffset of the tableView (or CollectionView) and setting the y position to 0 was doing this kind of behavior... so my fix was to set it to negative of the topBar height...

**Comment by NightWarrior** [comment]
Update: I found the reason why i could break it with the ios11 searchbar... turns out it could be broken without it as well... simply partially scrolling it was the problem... the insets werent updating there...

So i simply placed the new code inside the checkForParitalScroll() as well just below where you're setting the deltas...

      UIView.animate(withDuration: duration, delay: 0, options: UIViewAnimationOptions.beginFromCurrentState, animations: {
      self.updateSizing(delta)
      self.updateFollowers(delta)
      self.updateNavbarAlpha()
      
      // Adjust the top inset (useful when a table view has floating headers, see issue #219
      if let contentInset = self.scrollView()?.contentInset, let scrollInset = self.scrollView()?.scrollIndicatorInsets {
        self.scrollView()?.contentInset = UIEdgeInsets(top: contentInset.top - delta, left: 0, bottom: 0, right: 0)
        self.scrollView()?.scrollIndicatorInsets = UIEdgeInsets(top: scrollInset.top - delta, left: 0, bottom: 0, right: 0)
      }
    }, completion: nil)


Now i need help with the ios11 searchbar... your partial scroll seems to hold it stuck... while the natural behavior for ios11 searchbar is that it either collapses or extends fully depending on the amount of extension it had when scroll was let go.

**Comment by andreamazz** [comment]
Good point, I've updated the code to adjust the content inset after the partial scroll check.  
Can you share your code to setup the searchbar in the demo project so I can test that out?

**Comment by NightWarrior** [comment]
@andreamazz Just place this line in viewDidLoad() and the ios11 searchbar will be available


    self.navigationItem.searchController = UISearchController(searchResultsController: nil)

**Comment by andreamazz** [comment]
Ok, I see what you mean, this might be tricky to fix 🤔

**Comment by andreamazz** [comment]
Hey @NicholasTD07 
commit 1123b4e should fix the issue, thanks to @fralways . 
Let me know
